package com.meneses.budgethunter.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF0061A4)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFd1e4ff)
val md_theme_light_onPrimaryContainer = Color(0xFF001d36)
val md_theme_light_secondary = Color(0xFF535f70)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFd7e3f8)
val md_theme_light_onSecondaryContainer = Color(0xFF101c2b)
val md_theme_light_tertiary = Color(0xFF6c5e00)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFfce355)
val md_theme_light_onTertiaryContainer = Color(0xFF211c00)
val md_theme_light_error = Color(0xFFba1a1a)
val md_theme_light_errorContainer = Color(0xFFffdad6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFfdfcff)
val md_theme_light_onBackground = Color(0xFF1a1c1e)
val md_theme_light_surface = Color(0xFFfdfcff)
val md_theme_light_onSurface = Color(0xFF1a1c1e)
val md_theme_light_surfaceVariant = Color(0xFFdfe2eb)
val md_theme_light_onSurfaceVariant = Color(0xFF43474e)
val md_theme_light_outline = Color(0xFF73777f)
val md_theme_light_inverseOnSurface = Color(0xFFC3FBFF)
val md_theme_light_inverseSurface = Color(0xFF00373A)
val md_theme_light_inversePrimary = Color(0xFFfdfcff)
val md_theme_light_surfaceTint = Color(0xFFfdfcff)
val md_theme_light_outlineVariant = Color(0xFFD8C2BF)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFFFB4AB)
val md_theme_dark_onPrimary = Color(0xFF690004)
val md_theme_dark_primaryContainer = Color(0xFF930009)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDAD5)
val md_theme_dark_secondary = Color(0xFF87CEFF)
val md_theme_dark_onSecondary = Color(0xFF00344D)
val md_theme_dark_secondaryContainer = Color(0xFF004C6D)
val md_theme_dark_onSecondaryContainer = Color(0xFFC8E6FF)
val md_theme_dark_tertiary = Color(0xFF7CDA9C)
val md_theme_dark_onTertiary = Color(0xFF00391D)
val md_theme_dark_tertiaryContainer = Color(0xFF00522C)
val md_theme_dark_onTertiaryContainer = Color(0xFF97F7B6)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF002022)
val md_theme_dark_onBackground = Color(0xFF70F5FF)
val md_theme_dark_surface = Color(0xFF002022)
val md_theme_dark_onSurface = Color(0xFF70F5FF)
val md_theme_dark_surfaceVariant = Color(0xFF534341)
val md_theme_dark_onSurfaceVariant = Color(0xFFD8C2BF)
val md_theme_dark_outline = Color(0xFFA08C8A)
val md_theme_dark_inverseOnSurface = Color(0xFF002022)
val md_theme_dark_inverseSurface = Color(0xFF70F5FF)
val md_theme_dark_inversePrimary = Color(0xFFC00010)
val md_theme_dark_surfaceTint = Color(0xFFFFB4AB)
val md_theme_dark_outlineVariant = Color(0xFF534341)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFFF40018)
val shadow = Color(0x6A000000)
